FROM node:16


WORKDIR /app

COPY ./package.json /app
COPY ./package-lock.json /app

RUN npm install


COPY . /app/

RUN npx prisma generate
RUN npx prisma db push
RUN npx nx build api

EXPOSE 3333


CMD [ "node", "dist/apps/api/main.js" ];
