version: '3.8'

name: 'iot-data-storage'

services:
  client:
    image: iot-client
    build:
      dockerfile: ./Dockerfile.client
    ports:
      - 3001:8080
    volumes:
      - .:/app

  api:
    image: iot-api
    build:
      dockerfile: ./Dockerfile.api
    ports:
      - 3000:3333
    volumes:
      - .:/app
