FROM node:lts-alpine
RUN apk add g++ make py3-pip
RUN npm install -g http-server

WORKDIR /app

COPY . /app/

RUN npm install

RUN npx nx build client

EXPOSE 8080
CMD [ "http-server", "dist/apps/client" ]