FROM node:lts-alpine

RUN apk add g++ make py3-pip

WORKDIR /app

COPY ./package.json .
COPY ./package-lock.json .

RUN npm install

COPY . /app/

RUN npx prisma generate
RUN npx prisma db push
RUN npx nx build api

EXPOSE 3333


CMD [ "node", "dist/apps/api/main.js" ];
